### ISSUE TITLE
FaroRoutes support for RouterProvider react router v6

### ISSUE THREAD

**Issue by nosvalds** [grafana/faro-web-sdk#235] opened 2023-07-19 17:33 UTC
## Description

React Router v6 now uses a RouterProvider component that is passed an object from createBrowserRouter(). 

https://reactrouter.com/en/main/start/overview#client-side-routing

Trying to wrap the RouterProvider in FaroRoutes, 
```
import { FaroRoutes } from "@grafana/faro-react";

<FaroRoutes>
  <RouterProvider router={router} />
</FaroRoutes>
```
leads to the following error:

`Uncaught Error: useLocation() may be used only in the context of a <Router> component.`

## Proposed solution

Support the newest style of React Router definition.

## Context

https://reactrouter.com/en/main/upgrading/v6-data

**Comment by codecapitano** [comment] 2023-07-27 11:33
Thanks a lot @nosvalds. Would you mind adding the version of the Web-SDK you found the issue on?

Cheers,
Marco

**Comment by nosvalds** [comment] 2023-07-27 12:36
@grafana/faro-react=1.1.2
@grafana/faro-web-sdk=1.1.2

**Comment by barrykaplan** [comment] 2024-01-07 03:19
6 months old... ?? 
is there some workaround?

**Comment by barrykaplan** [comment] 2024-01-07 03:21
is this is intended solution: https://www.npmjs.com/package/@grafana/faro-react
readme says support for rhr v6

**Comment by eskirk** [comment] 2024-03-11 22:46
hi folks - sorry for the delay on this. this should get some attention in the coming weeks as we are moving to react router V6 for our internal plugin platform. 

again, sorry for the delay - we will discuss this in our prioritization meeting tomorrow.

**Comment by barrykaplan** [comment] 2024-05-02 19:27
I was going to try and update, but can't build this project. I can't seem to find any developer docs. Are they somewhere other than this repo?

**Comment by barrykaplan** [comment] 2024-05-02 19:37
Looks like this the top level block

```
              Types of property 'action' are incompatible.
                Type 'boolean | ActionFunction<any>' is not assignable to type '(...args: any[]) => any'.
                  Type 'boolean' is not assignable to type '(...args: any[]) => any'.
```

**Comment by barrykaplan** [comment] 2024-05-02 19:48
I rolled back to react-router-dom 6.6.2 and still the types don't match. Looking thru the code in this repo there no test or example that uses `withFaroRouterInstrumentation`. Is it possible that this never worked? The type `ActionFunction` has been in the react-router-dom from before this PR was created.

**Comment by codecapitano** [comment] 2024-05-03 07:42
Hey @barrykaplan we tested it with our Faro demo app and everything worked well.
There's a playground branch available.

I'll reopen this issue.

**Comment by codecapitano** [comment] 2024-05-03 08:12
@barrykaplan I can not reproduce the type issue.

What router are you using?

I tested all data routers again but it's working as expected.

createHashRouter,
createMemoryRouter,
createBrowserRouter
createMemoryRouter

Faro's `withFaroRouterInstrumentation` only subcribes to router events and returns the provided router.

example:

<img width="528" alt="image" src="https://github.com/grafana/faro-web-sdk/assets/47627413/f5a60d89-0367-4f4a-b2db-326134561e46">

Router version: `"react-router-dom": "6.6.2",`

**Comment by codecapitano** [comment] 2024-05-06 09:56
Can now reproduce the issue. 
Working on a fix.

**Comment by barrykaplan** [comment] 2024-05-16 15:46
@codecapitano Sorry for the late reply, but thanks for looking into this. Anything you need from me at this point?

**Comment by codecapitano** [comment] 2024-05-16 16:54
Hi @barrykaplan  We released an update which fixed the issues with the typings (v1.7.2).
See this [issue](https://github.com/grafana/faro-web-sdk/issues/582).

Do you still have this problem?

**Comment by barrykaplan** [comment] 2024-05-28 00:40
just back in the office
checking asap...

**Comment by codecapitano** [comment] 2024-05-28 07:36
> just back in the office checking asap...

Great thanks a lot 🙏

**Closed** 2024-05-29 15:04 UTC
Labels: bug
