### ISSUE TITLE
agent config

### ISSUE THREAD

**Issue by hellseyfer** [grafana/faro-web-sdk#93] opened 2023-01-12 13:43 UTC
Hello sir, I'm failing to connect to the domain the agent is exposing to start collecting data. May I be missing something?. This is my config:

  app_agent_receiver_configs:
    - autoscrape:
        enable: true
        metrics_instance: 'default'
      api_key: 'secret' # optional, if set, client will be required to provide it via x-api-key header
      instance: 'frontend'
      logs_instance: 'default'
      traces_instance: 'default'
      server:
        host: localhost
        port: 12345
        cors_allowed_origins:
          - https://localhost:3000
      logs_labels: # labels to add to loki log record
        app: frontend # static value
        kind: # value will be taken from log items. exception, log, measurement, etc
      logs_send_timeout: 5000
      sourcemaps:
        download: true # will download source file, extract source map location,
        # download source map and use it to transform stack trace locations

with this config page http://localhost:12345/collect is not found. tried with another host name but got the same result

**Comment by bfmatei** [comment] 2023-01-12 14:48
Hello,

Can you please edit your post and make it complaint with the bug template that we offer? We would also need a couple of more details regarding this.

- What version of the agent are you using?
- Are there any errors thrown by the agent?
- What are the reproducing steps for this?

The config is not properly formatted and it's pretty important in a YAML file. But looking at it, it seems that it is not compliant with the schema that we provide [here](https://grafana.com/docs/agent/latest/configuration/integrations/integrations-next/app-agent-receiver-config/)

**Comment by hellseyfer** [comment] 2023-01-12 21:33
I don't know what version I'm using but I just installed it following the windows integration commands.

Just checked the formatting with a website and seems to be ok, however, when I try to run the service, it throws an error. If I remove the app_agent_receiver_configs section everything works fine.

here's a copy of my agent-config.yaml without passwords
https://codebeautify.org/yaml-validator/y23250f52

**Comment by eskirk** [comment] 2023-08-14 23:28
@hellseyfer hi there - did you ever end up resolving this issue? doing some board triage and wondering if we need to investigate this further. let me know, thanks!

**Comment by codecapitano** [comment] 2024-02-16 11:17
Since it's open for a year now and has no more interaction, I am going to close the issue

**Closed by codecapitano** 2024-02-16 11:17 UTC
Labels: bug, question, triage/needs more info
