### ISSUE TITLE
Error when sending data to the server when body size > 64kb and keepalive fetch option enable.

### ISSUE THREAD

**Issue by AMontagu** [grafana/faro-web-sdk#192] opened 2023-05-15 17:31 UTC
## Description

The issue come from the keepalive options in the FetchTransport: https://github.com/grafana/faro-web-sdk/blob/88011e78770c1821a81203c46966b6032addc1ec/packages/web-sdk/src/transports/fetch/transport.ts#L55

When removing it the bug disapear.

This bug **only happen** when:
- Using DocumentLoadInstrumentation from @opentelemetry/instrumentation-document-load
- Spliting chunk (https://webpack.js.org/plugins/split-chunks-plugin/) whatever configuration
- Using FetchInstrumentation from @opentelemetry/instrumentation-fetch
- Using BatchSpanProcessor from @opentelemetry/sdk-trace-base
- Using XMLHttpRequestInstrumentation from @opentelemetry/instrumentation-xml-http-request

![Screenshot from 2023-05-15 17-31-28](https://github.com/grafana/faro-web-sdk/assets/11883225/3cd8e2a7-3dae-4be3-9933-6c0e87c8f463)

## Steps to reproduce

Using all informations said above to configure faro and your project.

## Expected behavior

Trace corretly exported.

## Actual behavior

Trace are not exported because of the error screenshot in description

## Environment

- **SDK version:** 1.0.2
- **SDK instrumentations:** 1.0.2
- **Device type:** computer
- **Device name:** Dell inspiron
- **OS:** Ubuntu 20.04
- **Browser:** Chrome latest

## Demo

It is working fine without customizing splitChunks on the same projet with a npm run serve in local. (Possibility that is not working with a build as it's the default configuration)

If I copy paste the load as curl in terminal it is working fine. 
If I copy past as fetch and use it directly in my code it's working fine.

If I use the SimpleSpanProcessor it's working.

The request block in pending even if the promise already rejected:
![Screenshot from 2023-05-15 18-25-26](https://github.com/grafana/faro-web-sdk/assets/11883225/2aec0409-8471-47bc-951a-1e64704adf7b)

Other call to grafana-agent in the same page are working fine.

In the zone.js:975 file from the stack trace the line is: `return patchDelegate(this, arguments);`
If I do a `console.log(patchDelegate, this, arguments)`
I get:
![Screenshot from 2023-05-15 18-34-26](https://github.com/grafana/faro-web-sdk/assets/11883225/206ab13a-08dc-4fc8-a52e-8b49fe22fd4f)

Important to note the `Exception: TypeError:` in the callee do not appear just here but in other above call so it can be a wrong path to follow

In the fetch.js:233 file from the stack trace the line is: `return original.apply(this, args);` -> The issue STILL happen when we remove the fetch instrumentation
If I do a `console.log(original, original.apply, this, args)`
I get:
![Screenshot from 2023-05-15 18-41-44](https://github.com/grafana/faro-web-sdk/assets/11883225/57010b12-a578-4d1d-8dab-0ce0a977cf70)

**Comment by codecapitano** [comment] 2023-05-30 08:28
Hi @AMontagu,

I have no idea yet what we can do about this. 
This seems to be related to the OTel-JS package (in combination with Faro?), did you maybe also had a look at the OTel issues?

I scanned the last OTel-JS releases to find out if this may be fixed with one of the last releases.
But in the respective READMEs I could not find anything  related.
So we need to investigate further.

Looking at [this issue](https://github.com/grafana/faro-web-sdk/issues/201) it seems that other users have similar problems.

Not the very best answer but that's the current state of research :(

Cheers,
Marco

**Comment by AMontagu** [comment] 2023-05-30 09:20
Hi @codecapitano 

Thanks for the answer. Yes indeed it is a really strange issue. Is it possible to have more explanation about the keepalive option in the fetch ? Maybe having it optional can provide a quick workaround even if it mean loosing some trace if user close tabs while processing.

I looked at the issue this is not what happen to me even if I use all the dependencies listed in the issue and the same version of faro (difference I am on Vue 2.7 and he is on Vue 2.6). The other issue look like import issue. The vue stack trace display the Zone Context in all new error even if not related. Maybe it is just a wrong use of the package.

I can open an issue in OTel-JS package but the line raising the issue if the fetch call using the keepalive in the faro code. 

What I can do is maybe try to make a minimal reproduction repo so that you can verify the issue and create one in OTel-JS package. (It will also allow us to be sure it is not something from my code)

**Comment by codecapitano** [comment] 2023-05-30 10:23
Hi @AMontagu 

The `keepalive` option is to make fetch outlive navigations, so it basically acts like `sendBeacon`.
This means that the data will still be sent even if a user navigates away from the site. 
Therefore it is mostly used for analytics data to ensure that we don't have any data loss.
`Fetch` with `keepalive` is the replacement for `sendBeacon`

> I can open an issue in OTel-JS package but the line raising the issue if the fetch call using the keepalive in the faro code.

Hmm maybe not yet. I too have the strong impression that this happens when used together with Faro because I could not find any issues in their GH page.

>What I can do is maybe try to make a minimal reproduction repo so that you can verify the issue and create one in OTel-
JS package. (It will also allow us to be sure it is not something from my code)

An example where we can reproduce the issue would be awesome ❤️ 


**Maybe as a quick fix if the issue with the fix is tolerable:**
In [this issue ](https://github.com/grafana/faro-web-sdk/issues/201) the opener also reports problems with Zone and Vue. He replaced the `ZoneContextManager` with the `StackContextManager.` But there is one problem with that approach because [StackContextManager does not fully support the async calls](https://open-telemetry.github.io/opentelemetry-js/classes/_opentelemetry_sdk_trace_web.StackContextManager.html)!.

Cheers,
Marco

**Comment by codecapitano** [comment] 2023-05-31 07:40
Hey thanks a lot @alioshr 

Even though I have isolated faro instances, when I unmount a remote App and switch to another one I still see requests being sent to the collector from the unmounted "isolated" instance.

> `keepalive` would send all remaining/pending requests even a app is unmounted or a user navigates away from a page.
This is to ensure that no data got lost. 

> Why might turning keepAlive off stop the errors? Because Although leaving the app where the isolated instance is + turning keepAlive: false still keeps the fetch requests from the isolated instances active. So not sure how is it helping 

Yes I'm also very confused by this problem. 

My current idea is that we may run into the the body size limit for `keepalive` requests (64kiB). If this limit is reached fetch returns a network error.

No good news yet but we'll fix it eventually.

**Comment by AMontagu** [comment] 2023-05-31 13:43
@codecapitano I think you hit the good point for 64kiB. As it happen only when trace are at a specific size.

We had some issues to reproduce because in an empty project we didn't raise this size. 
Busy until friday but will definitely try to flood traces with a lot of data to see if it raise the issue.

**Comment by codecapitano** [comment] 2023-06-01 07:20
> @codecapitano I think you hit the good point for 64kiB. As it happen only when trace are at a specific size.
> 
> We had some issues to reproduce because in an empty project we didn't reach this size. Busy until friday but will definitely try to flood traces with a lot of data to see if it raise the issue.

Awesome and thanks for testing this. Please keep use updated with the results of your test runs.
It may also be very intersting for the otel project to share the results—in case the keepalive issue is related to trace sizes.

Cheers,
Marco

**Comment by codecapitano** [comment] 2023-06-01 07:26
> > My current idea is that we may run into the the body size limit for `keepalive` requests (64kiB). If this limit is reached fetch returns a network error.
> 
> Hi @codecapitano <3. Thank you for so much help on this meanwhile =) I have been bugging you everywhere
> 
> Shouldn't we expect the usage of `isolate: true` along with `keepalive: false` to result in fully isolated faro instances? Shouldn't stop transporting whatever was kept active when isolating the instance & leaving an app?

Hey @alioshr no no it's absolutely no bugging at all! We at Grafana and of course myself too are very very happy about all the input we receive. It's absolutely stunning for us how the community cares and invests time to help us improve things. ❤️ So please keep asking and raise issues :)

> Shouldn't we expect the usage of isolate: true along with keepalive: false to result in fully isolated faro instances?

In case you mean by "fully isolated" that all pending requests are dropped once the app is unmounted or euser leaves the page then I would say yes. But this would also mean that you loose some data points aka signals.

Cheers,
Marco

**Comment by AMontagu** [comment] 2023-06-01 15:55
Hello @codecapitano 

here is a minimal repo: https://github.com/Mike-FR/faro-keepalive thanks to my coworker @Mike-FR

The error happen when you click on the button. We confirm that sending a log with more than 65 535 char (64kb) or 2 with more than 33 000 char make the problem happen.

If we can help on something tell me.

Also do you want me to rename the issue to be more close to the reality ?

**Comment by codecapitano** [comment] 2023-06-02 07:16
Hi @AMontagu 

Very cool thank you. I think It's a good step forward that we are now able to better isolate the problem.
Thanks a lot you and your company for validating this.

Having the repo in place will make working on this a lot easier, thanks so much @Mike-FR!
Will have a look on Monday.

> If we can help on something tell me.

As always thanks a lot and I'll tell you of course :)

> Also do you want me to rename the issue to be more close to the reality ?

Very good idea!


Cheers
Marco

**Comment by AMontagu** [comment] 2023-06-02 10:20
Perfect @codecapitano 

So I am not an expert on that specific domain. But I wanted to look a bit just to understand and so I have input that may be wrong but in case in can help your thought I share them.

Firstly, I think keepalive and sendBeacon share same limitation, so replacing it by sendBeacon is not the solution.

Secondly, even by spliting the call it look like it's not working: https://chromium.googlesource.com/chromium/src/+/c1a211aa583ade023aca652e9493c01603623aa3/third_party/WebKit/LayoutTests/http/tests/sendbeacon/beacon-allowance-limit.html

Hacking methods that prevent the unload of the page while transfering the data is not a solution for a tools like grafana faro that should address all need of differents companies.

It less us with not that much options.

- Accepting loosing data if trace too big.
- Complexifying the all thing by (using web worker)[https://rleiwang.medium.com/instrument-web-app-with-opentelemetry-using-web-worker-212161a299e9]. May be hard to do it in a librairie as it's more an end user decision but may let the possibility to keep trace and log in offline PWA session (that we actually use in ou company)
- Setting a limit of 64kb for each request by default. That is a really small body size actually for big applications.
- Anything you can find that I didn't

**Comment by codecapitano** [comment] 2023-06-02 12:59
Hey @AMontagu 

> Firstly, I think keepalive and sendBeacon share same limitation, so replacing it by sendBeacon is not the solution.

This is correct

> Hacking methods that prevent the unload of the page while transferring the data is not a solution for a tools like grafana faro that should address all need of differents companies.

Exactly.


Note:
I researched a bit further and found an [old issue for otel-js where the issuer had the same size limit problem](https://github.com/open-telemetry/opentelemetry-js/issues/1593).

Turns out the otel folks provide an [option to switch from `sendBeacon` to `xhr` in the exporters](https://github.com/open-telemetry/opentelemetry-js/blob/1fc4ac652fcfedc67d1e6dbb1a22d345325baeee/experimental/packages/otlp-exporter-base/src/platform/browser/OTLPExporterBrowserBase.ts#L40).

Maybe we can provide an option to turn off `keepalive` and use standard fetch for cases like yours. 
This will indeed leave us with the problem that pending requests won't outlive the page and we may loose some signals. 
Maybe it's negligible, but it's still a thing to consider. 

We are currently working on a own [FetchInstrumentation](https://github.com/grafana/faro-web-sdk/pull/200) and will provide more instrumentations in the future. 
We also will provide a mechanism which let's you map UI events and Fetch requests etc. to backend traces. 
The Faro payload is smaller compared to the otel format so we may not hit the body size limit that quick. This may mitigate the problem a bit if you not rely on the otel protocol format / tracing and use Faro instruments instead once they are available.


But anyways we want both to work equally well with Faro so we of course we will try to find a suitable solution.

Cheers,
Marco

**Comment by AMontagu** [comment] 2023-09-20 15:57
Hello @codecapitano 

Have you any update on this ? we miss a lot of trace and log because of this limitation.

**Comment by codecapitano** [comment] 2023-09-21 07:19
Hi @AMontagu sorry unfortunately I have no updates on this. 
We already thought internally about hoe to tackle it and have some ideas.

A precondition is to tackle this issue and then we can build on top of it: https://github.com/grafana/faro-web-sdk/issues/261

**Closed** 2023-10-27 06:57 UTC
Labels: bug
