### ISSUE TITLE
Cannot run demo, bad node version 16.20.2 to install rollup@4.02

### ISSUE THREAD

**Issue by dyllandry** [grafana/faro-web-sdk#350] opened 2023-10-20 19:57 UTC
## Description

I tried to run the demo using `docker compose --profile demo up -d` and it throws an error when running the Dockerfile.

## Steps to reproduce

1. Pull faro-web-sdk repo
2. run `docker compose --profile demo up -d`

## Expected behavior

The docker services to start up.

## Actual behavior

I got this error. Included some logs around it:

```
...

 => CACHED [demo 26/37] COPY experimental/instrumentation-fetch/package.json      exper  0.0s
 => CACHED [demo 27/37] RUN mkdir experimental/instrumentation-fetch/src                 0.0s
 => CACHED [demo 28/37] RUN cp index.ts experimental/instrumentation-fetch/src           0.0s
 => CACHED [demo 29/37] COPY experimental/instrumentation-xhr/package.json      experim  0.0s
 => CACHED [demo 30/37] RUN mkdir experimental/instrumentation-xhr/src                   0.0s
 => CACHED [demo 31/37] RUN cp index.ts experimental/instrumentation-xhr/src             0.0s
 => CACHED [demo 32/37] RUN rm index.ts                                                  0.0s
 => ERROR [demo 33/37] RUN SKIP_GEN_VERSION=1 yarn install --pure-lockfile              19.9s
------
 > [demo 33/37] RUN SKIP_GEN_VERSION=1 yarn install --pure-lockfile:
0.176 yarn install v1.22.19
0.244 [1/4] Resolving packages...
0.499 [2/4] Fetching packages...
19.50 error rollup@4.0.2: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.20.2"
19.51 error Found incompatible module.
19.51 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: process "/bin/sh -c SKIP_GEN_VERSION=1 yarn install --pure-lockfile" did not complete successfully: exit code: 1
```

## Environment

- **SDK version:** I cloned from master, current commit is [a0d6366](https://github.com/grafana/faro-web-sdk/commit/a0d6366150130f563a300da08d97459fe753f45f)
- **SDK instrumentations:** N/A
- **Device type:** Laptop
- **Device name:** MacBook Pro
- **OS:** Ventura 13.5.2 (22G91)
- **Browser:** N/A

## Context
I saw rollup 4 needs node 18 in their upgrade docs. I noticed too that the Dockerfile specifies `node:16-alpine`. I tried out `node:18-alpine` and the yarn install step succeeded.

**Comment by codecapitano** [comment] 2023-10-23 07:55
Hi @dyllandry 

We switched to the current LTS vesion of Node (^18).
[V16 is end of life](https://nodejs.org/en/blog/announcements/nodejs16-eol). 

If you set up [nvm to auto-switch to the configured node version for the project](https://github.com/nvm-sh/nvm#deeper-shell-integration) it will automatically download and run node 18 [as defined in the .nvrmc file](https://github.com/grafana/faro-web-sdk/blob/a0d6366150130f563a300da08d97459fe753f45f/.nvmrc#L1).

So you also need node 18 installed to run Faro.

Let me know if this works or if you have any questions.

Cheers,
Marco

**Comment by codecapitano** [comment] 2023-10-23 08:04
Hi @dyllandry 

Unfortunately I can not reproduce the issue.
Do you use nvm so it automatically switches to Node 18 when you are in the Faro directory?

**Background:**
We switched to the current LTS vesion of Node (^18).
[V16 is end of life](https://nodejs.org/en/blog/announcements/nodejs16-eol). 

If you set up [nvm to auto-switch to the configured node version for the project](https://github.com/nvm-sh/nvm#deeper-shell-integration) it will automatically download and run node 18 [as defined in the .nvrmc file](https://github.com/grafana/faro-web-sdk/blob/a0d6366150130f563a300da08d97459fe753f45f/.nvmrc#L1).

Let me know if this works.

Cheers,
Marco

**Comment by codecapitano** [comment] 2023-10-23 08:55
Hi @dyllandry 

thanks for reporting the issue. 
The node version used in the Dockerfile was not updated when we switched to the current Node LTS version.

After fixed it, pruned docker and pulled/build/started the demo without any problems.

Can you confirm if the issue is fixed for you?

Cheers,
Marco

**Comment by dyllandry** [comment] 2023-10-24 19:37
Yup, it's working now! Thanks for updating that.

**Comment by codecapitano** [comment] 2023-10-25 07:15
> Yup, it's working now! Thanks for updating that.

Thanks for the update @dyllandry. 🙏 
Will close the issue.

**Closed by codecapitano** 2023-10-25 07:15 UTC
Labels: bug
